
name: Run autotests


on:
  workflow_dispatch:
    inputs:
      deployment_target:
        desciption: select tests to run
        required: true
        type: choice
        default: all
        options:
          - all


jobs:
  run-tests: ubuntu-latest
  name: Tests
  steps:
    - name: Copy source code
      uses: actions/chechout@v4
    - name: Set up Python env
      uses: actions/setup-pyhon@v5
      with:
        python-version: "3.14"
    - name: install dependencies
      run: pip install -r requirements.txt
    - name: Run tests
      run: pytest -v
